name: Terraform CI/CD
on:
    push:
        branches:
        - main
    pull_request:
      branches:
        - main

jobs:
    terraform:
        name: "Terraform Workflow"
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Format
          run: terraform fmt -write=true

        - name: Terraform Format Check
          run: terraform fmt -check

        - name: Terraform Init
          run: terraform init
        
        - name: Terraform Validate
          run: terraform validate
        
        - name: Terraform Plan
          run: terraform plan -out=tfplan.binary -input=false -var-file=terraform.tfvars

        - name: Convert Terraform Plan to JSON
          run: terraform show -json tfplan.binary > tfplan.json
        
        - name: Install Sentinel
          run: |
            curl -sSL https://releases.hashicorp.com/sentinel/0.29.0/sentinel_0.29.0_linux_amd64.zip -o sentinel.zip
            unzip sentinel.zip
            sudo mv sentinel /usr/local/bin/
            sentinel --version
            
        - name: Run Sentinel Policies
          run: sentinel apply -config=sentinel.hcl

        - name: Terraform Apply
          run: terraform apply -auto-approve tfplan.binary

        - name: Terraform Destroy (Manual Approval)
          if: github.ref == 'refs/heads/main'
          run: terraform destroy -auto-approve
