name: Terraform CI/CD
on:
    push:
        branches:
        - main
    pull_request:
      branches:
        - main

jobs:
    terraform:
        name: "Terraform Workflow"
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Format
          run: terraform fmt -write=true

        - name: Terraform Format Check
          run: terraform fmt -check

        - name: Terraform Init
          run: terraform init
        
        - name: Terraform Validate
          run: terraform validate
        
        - name: Terraform Plan
          run: terraform plan -out=tfplan.binary

        - name: Convert Terraform Plan to JSON
          run: terraform show -json tfplan.binary > tfplan.json
  
        - name: Run Sentinel Policies
          run: sentinel apply -config=sentinel.hcl

        - name: Security Scan with Terraform Sentinel
          run: sentinel apply --exit-status

        - name: Terraform Apply
          run: terraform apply -auto-approve tfplan.binary

        - name: Terraform Destroy (Manual Approval)
          if: github.ref == 'refs/heads/main'
          run: terraform destroy -auto-approve
