data "github_repository_file" "terraform" {
  repository = "github-actions-demo"
  file  = ".github/workflows/terraform.yml"
  content = <<EOT

name: Terraform CI/CD

on:
    push:
        branches:
        - main
    pull_request:
      branches:
        - main

jobs:
    terraform:
        name: "Terraform Workflow"
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.0.0
        
        - name: Terraform Format
          run: terraform fmt -check

        - name: Terraform Init
          run: terraform init
        
        - name: Terraform Validate
          run: terraform validate
        
        - name: Security Scan with Terraform Sentinel
          run: sentinel apply --exit-status

        
        - name: Terraform Plan
          run: terraform plan
        
        - name: Terraform Apply
          run: terraform apply -auto-approve
        
        - name: Terraform Destroy (Manual Approval)
        if: github.ref == 'refs/heads/main'
        run: terraform destroy -auto-approve

EOT
}